set_project("VCX-Labs")
set_version("2.0.0-alpha.1")
set_xmakever("2.6.9")
set_languages("cxx20")

add_rules("mode.debug", "mode.release")

add_requires("glad")
add_requires("glfw")
add_requires("glm")
add_requires("imgui")
add_requires("spdlog")
add_requires("stb")
add_requires("fmt")

target("assets")
    set_kind("phony")
    set_default(true)
    after_build(function (target)
        os.mkdir(path.join(target:targetdir(), "assets"))
        os.cp("assets", target:targetdir())
    end)
    after_install(function (target)
        os.mkdir(path.join(target:installdir(), "bin", "assets"))
        os.cp("assets", path.join(target:installdir(), "bin"))
    end)
    after_clean(function (target)
        os.rm(path.join(target:targetdir(), "assets"))
    end)

target("engine")
    set_kind("static")
    add_packages("glad"  , { public = true })
    add_packages("glfw"  , { public = true })
    add_packages("glm"   , { public = true })
    add_packages("imgui" , { public = true })
    add_packages("spdlog", { public = true })
    add_packages("stb"   , { public = true })
    add_packages("fmt"   , { public = true })

    add_includedirs("src/3rdparty", { public = true })
    add_includedirs("src/VCX"     , { public = true })
    add_headerfiles("src/3rdparty/**.h")
    add_headerfiles("src/3rdparty/**.hpp")
    add_files      ("src/3rdparty/**.cpp")
    add_headerfiles("src/VCX/Engine/**.h")
    add_headerfiles("src/VCX/Engine/**.hpp")
    add_files      ("src/VCX/Engine/**.cpp")
    add_headerfiles("src/VCX/Assets/**.hpp")

target("lab-common")
    set_kind("static")
    add_deps("engine")
    add_deps("assets")
    add_headerfiles("src/VCX/Labs/Common/*.h")
    add_files      ("src/VCX/Labs/Common/*.cpp")

target("lab1")
    set_kind("binary")
    add_deps("lab-common")
    add_headerfiles("src/VCX/Labs/1-Drawing2D/*.h")
    add_headerfiles("src/VCX/Labs/1-Drawing2D/*.hpp")
    add_files      ("src/VCX/Labs/1-Drawing2D/*.cpp")
